using System.Diagnostics;
using Microsoft.Extensions.Options;
using ReliableWebhook.Application;
using ReliableWebhook.Domain;
namespace ReliableWebhook.Worker;

public sealed class DeliveryOptions { public int BatchSize { get; set; } = 20; public int MaxAttempts { get; set; } = 10; public int PollIntervalMilliseconds { get; set; } = 1000; public int RequestTimeoutSeconds { get; set; } = 10; public int LeaseSeconds { get; set; } = 60; public int InitialRetrySeconds { get; set; } = 5; public int MaximumRetrySeconds { get; set; } = 3600; }
public sealed class DeliveryWorker(IServiceScopeFactory scopes, IHttpClientFactory clients, IOptions<DeliveryOptions> options, ILogger<DeliveryWorker> log) : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken) { var o = options.Value; while (!stoppingToken.IsCancellationRequested) { try { using var scope = scopes.CreateScope(); var store = scope.ServiceProvider.GetRequiredService<IWebhookStore>(); var items = await store.ClaimAsync(o.BatchSize, TimeSpan.FromSeconds(o.LeaseSeconds), o.MaxAttempts, stoppingToken); foreach (var item in items) await Send(item, store, o, stoppingToken); if (items.Count == 0) await Task.Delay(o.PollIntervalMilliseconds, stoppingToken); } catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested) { break; } catch (Exception ex) { log.LogError(ex, "Delivery polling failed"); await Task.Delay(o.PollIntervalMilliseconds, stoppingToken); } } }
    async Task Send(ClaimedDelivery i, IWebhookStore store, DeliveryOptions o, CancellationToken stop) { var n = i.AttemptCount + 1; var sw = Stopwatch.StartNew(); int? code = null; string? error = null; try { using var timeout = CancellationTokenSource.CreateLinkedTokenSource(stop); timeout.CancelAfter(TimeSpan.FromSeconds(o.RequestTimeoutSeconds)); using var req = new HttpRequestMessage(HttpMethod.Post, i.DestinationUrl) { Content = new StringContent(i.Payload, System.Text.Encoding.UTF8, "application/json") }; req.Headers.Add("X-Webhook-Event", i.EventType); req.Headers.Add("X-Webhook-Delivery", i.Id.ToString()); req.Headers.Add("X-Webhook-Signature", "sha256=" + WebhookSigner.Sign(i.Secret, i.Payload)); using var response = await clients.CreateClient("webhooks").SendAsync(req, timeout.Token); code = (int)response.StatusCode; if (response.IsSuccessStatusCode) { await store.CompleteAsync(i, n, code.Value, (int)sw.ElapsedMilliseconds, stop); return; } error = $"HTTP {code}"; } catch (OperationCanceledException) when (!stop.IsCancellationRequested) { error = "Request timed out"; } catch (HttpRequestException ex) { error = ex.Message.Length > 400 ? ex.Message[..400] : ex.Message; } var terminal = n >= i.MaxAttempts; var next = DateTimeOffset.UtcNow + RetryPolicy.Delay(n, TimeSpan.FromSeconds(o.InitialRetrySeconds), TimeSpan.FromSeconds(o.MaximumRetrySeconds)); await store.FailAsync(i, n, code, error ?? "Delivery failed", (int)sw.ElapsedMilliseconds, next, terminal, stop); }
}
