<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../ReliableWebhook.Application/ReliableWebhook.Application.csproj" />
    <ProjectReference Include="../ReliableWebhook.Domain/ReliableWebhook.Domain.csproj" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference
      Include="Microsoft.Extensions.DependencyInjection.Abstractions"
      Version="10.0.2"
    />
    <PackageReference
      Include="Microsoft.Extensions.Options.ConfigurationExtensions"
      Version="10.0.2"
    />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations/*.sql" />
  </ItemGroup>
</Project>
